In [2]:
import torch

In [3]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


# Pytorch 101 & Recall Linear Algebra

> basically in the deep learning theory it is based to study many methodologies of deep learning for learning linear algebra theory.

> so before studying deep learning, it will be affect to many benefits to understand many techinque to recall linear algebra with application of pytorch. 

## Tensor initialization

In [5]:
import torch
import numpy as np

In [140]:
def print_info(tensor):
    print("dtype : ", tensor.dtype)
    print("element \n", tensor)
    print("dimension : ", tensor.ndim)
    print("shape : ", tensor.shape)
    

In [7]:
l1 = [1,2,3]
t1 = torch.Tensor(l1)
print_info(t1)

dtype :  torch.float32
element :  tensor([1., 2., 3.])
dimension :  1
shape :  torch.Size([3])


In [8]:
l2 = [1,2,3]
t2 = torch.tensor(l2)
print_info(t2)

dtype :  torch.int64
element :  tensor([1, 2, 3])
dimension :  1
shape :  torch.Size([3])


In [9]:
l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)
print_info(t3)

dtype :  torch.int64
element :  tensor([1, 2, 3])
dimension :  1
shape :  torch.Size([3])


In [10]:
l1[0] = 100
l2[0] = 100
l3[0] = 100


In [11]:
print_info(t1)
print("")
print_info(t2)
print("")
print_info(t3)


dtype :  torch.float32
element :  tensor([1., 2., 3.])
dimension :  1
shape :  torch.Size([3])

dtype :  torch.int64
element :  tensor([1, 2, 3])
dimension :  1
shape :  torch.Size([3])

dtype :  torch.int64
element :  tensor([1, 2, 3])
dimension :  1
shape :  torch.Size([3])


---
### check point
torch.Tensor -> class
- input : int
- output : float

torch.tensor -> function
torch.as_tensor -> function
- input : int
- ouput : int
---

## Tensor costnat value initialization 

In [12]:
t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [13]:
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])



tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [14]:

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

#empty method creat a tensor without initilizing its value


tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])


`torch.empty()` vs `torch.zeros()`

- empty method : creat a tensor without initilizing its value
- zeros method : create a tensor with initilizing zero value

In [15]:
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


`torch.eye()` function return a 2-D tensor with ones on the diagonal and zeros elsewhere.

## Tensor initilization random values

| Function          | Description                                   | Parameters                               |
| ----------------- | --------------------------------------------- | ---------------------------------------- |
| `torch.randint`   | Generate random integers within a range.     | `low`, `high`, `size`                    |
| `torch.rand`      | Generate random numbers from a uniform distribution. | `size`                             |
| `torch.randn`     | Generate random numbers from a normal (Gaussian) distribution. | `size`                             |
| `torch.normal`    | Generate random numbers from a normal distribution with specified mean and standard deviation. | `mean`, `std`, `size`              |
| `torch.linspace`  | Create a tensor of evenly spaced values over a specified range. | `start`, `end`, `steps`            |
| `torch.arange`    | Create a tensor with values from a start value to an end value with a specified step size. | `end`, `step`                       |
| `torch.manual_seed` | Set the seed for random number generation to ensure reproducibility. | `seed`                               |


torch.randint

In [16]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

tensor([[14, 19]])


torch.rand

In [17]:
t2 = torch.rand(size=(1, 3))
print(t2)


tensor([[0.2514, 0.0235, 0.4803]])


torch.randn

In [18]:
t3 = torch.randn(size=(1, 3))
print(t3)

tensor([[-0.3926, -0.7575, -0.3954]])


torch.normal

In [19]:
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)


tensor([[ 9.7490,  9.9106],
        [10.8769, 10.6630],
        [ 8.9946, 10.9254]])


torch.linspace

In [20]:
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)


tensor([0.0000, 2.5000, 5.0000])


torch.arange

In [21]:
t6 = torch.arange(5)
print(t6)

tensor([0, 1, 2, 3, 4])


torch.manual_seed

In [22]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


> it will be made same result if use same seed with manual_seed function from each instance

## Tensor type conversion


| Data Type      | Description              |
|----------------|--------------------------|
| `torch.float16` | 16-bit floating point   |
| `torch.float32` | 32-bit floating point   |
| `torch.float64` | 64-bit floating point   |
| `torch.double`  | Alias for `torch.float64`|
| `torch.int8`    | 8-bit signed integer    |
| `torch.int16`   | 16-bit signed integer   |
| `torch.short`   | Alias for `torch.int16`  |
| `torch.int32`   | 32-bit signed integer   |
| `torch.int64`   | 64-bit signed integer   |
| `torch.uint8`   | 8-bit unsigned integer  |
| `torch.bool`    | Boolean (True/False)    |

In this updated list, `torch.double` and `torch.short` are included as aliases for their respective data types, making it clear that they are commonly used alternatives.

In [23]:
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [24]:
print("-----Parameter------")
double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)

print("-----Method------")
double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()
print(double_d.dtype)
print(short_e.dtype)

print("-----'to'Method------")
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)

print("-----After Calculate------")
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

-----Parameter------
torch.float64
torch.int16
-----Method------
torch.float64
torch.int16
-----'to'Method------
torch.float64
torch.int16
-----After Calculate------
torch.float64


## Tensor Operation

a chart summarizing common tensor operations in PyTorch:

| Operation                      | Description                                 | Example                                           |
| ------------------------------ | ------------------------------------------- | ------------------------------------------------- |
| Addition (`+`, `.add()`)       | Adds two tensors element-wise.              | `result = tensor1 + tensor2`<br>`result = torch.add(tensor1, tensor2)` |
| Subtraction (`-`, `.sub()`)    | Subtracts one tensor from another element-wise. | `result = tensor1 - tensor2`<br>`result = torch.sub(tensor1, tensor2)` |
| Multiplication (`*`, `.mul()`) | Multiplies two tensors element-wise.         | `result = tensor1 * tensor2`<br>`result = torch.mul(tensor1, tensor2)` |
| Division (`/`, `.div()`)       | Divides one tensor by another element-wise. | `result = tensor1 / tensor2`<br>`result = torch.div(tensor1, tensor2)` |
| Matrix Multiplication (`@`, `.matmul()`) | Performs matrix multiplication between two tensors. | `result = tensor1 @ tensor2`<br>`result = torch.matmul(tensor1, tensor2)` |
| Element-wise Power (`**`, `.pow()`) | Raises a tensor to a specified power element-wise. | `result = tensor1 ** exponent`<br>`result = torch.pow(tensor1, exponent)` |
| Element-wise Square Root (`** 0.5`, `.sqrt()`) | Calculates the square root of a tensor element-wise. | `result = tensor1 ** 0.5`<br>`result = torch.sqrt(tensor1)` |
| Summation (`sum()`, `.sum()`)  | Computes the sum of all elements in a tensor or along specified dimensions. | `total = tensor1.sum()`<br>`total = torch.sum(tensor1, dim=1)` |
| Mean (`mean()`, `.mean()`)     | Calculates the mean (average) of elements in a tensor or along specified dimensions. | `avg = tensor1.mean()`<br>`avg = torch.mean(tensor1, dim=0)` |
| Max (`max()`, `.max()`)        | Finds the maximum value in a tensor or along specified dimensions. | `max_val = tensor1.max()`<br>`max_val = torch.max(tensor1, dim=1)` |
| Min (`min()`, `.min()`)        | Finds the minimum value in a tensor or along specified dimensions. | `min_val = tensor1.min()`<br>`min_val = torch.min(tensor1, dim=0)` |

### Sample Code

In [25]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [26]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


## Tensor Matrix Multiplcation Operation 

* dot product

In [29]:
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

tensor(7) torch.Size([])


* Matrix Multiplication

In [30]:
# 2X3 * 3X2

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


* multi dimensional matrix multiplication

In [31]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

torch.Size([10, 3, 5])


## Tensor Operation Matmul

| Operation Type             | Description and Learning Objectives                 |
| ---------------------------| --------------------------------------------------- |
| Vector x Vector            | Understand dot product computation and resulting tensor shape. |
| Matrix x Vector            | Explore broadcasting in matrix-vector multiplication and its impact on tensor dimensions. |
| Batched Matrix x Vector    | Grasp the concept of batched matrix-vector multiplication and efficient handling of multiple instances. |
| Batched Matrix x Batched Matrix | Learn batch matrix multiplication (`bmm`) with two batches of matrices and understand the resulting tensor shape. |
| Batched Matrix x Matrix    | Demonstrate batch matrix multiplication when one matrix is shared across batches. |

---
> what is borad cast?

Broadcasting is a powerful feature in PyTorch that simplifies element-wise operations between tensors of different shapes. It allows for automatic alignment of dimensions, making tensors compatible without the need for explicit reshaping.

---

- Vector x Vector

In [32]:
t1 = torch.randn(3)
t2 = torch.randn(3)
result = torch.matmul(t1, t2)
print_info(result)

dtype :  torch.float32
element :  tensor(-3.9578)
dimension :  0
shape :  torch.Size([])


- Matrix x Vector

In [33]:
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
result = torch.matmul(t3, t4)

print_info(result)

dtype :  torch.float32
element :  tensor([ 0.4829,  2.7321, -0.1362])
dimension :  1
shape :  torch.Size([3])


- batched matrix x Vector

In [34]:
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
result = torch.matmul(t5, t6)

print_info(result)

dtype :  torch.float32
element :  tensor([[-5.2011,  3.4575, -1.3185],
        [ 0.7632,  1.6519, -2.1533],
        [ 1.2427, -2.0782, -1.0614],
        [-1.4175, -2.0767,  3.8303],
        [ 1.7279, -0.0849,  1.1593],
        [-1.6880, -0.7415,  3.2048],
        [-2.9646,  0.6164, -1.0502],
        [-0.2039,  1.7261,  0.5722],
        [ 0.4179, -2.4676, -1.1504],
        [-1.6703,  1.9097, -0.1249]])
dimension :  2
shape :  torch.Size([10, 3])


- batched matrix x batched matrix

In [35]:
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
result = torch.matmul(t7, t8)

print_info(result)

dtype :  torch.float32
element :  tensor([[[ 2.1020, -0.3041,  1.1571,  0.2306, -1.4742],
         [-3.2551,  0.9498,  0.8669, -0.4856,  1.4879],
         [ 0.2347, -1.1390,  0.0816, -1.8079,  0.3185]],

        [[-0.5076, -0.7116,  0.1923, -5.5040, -3.2326],
         [-1.0604,  1.5960,  0.1538,  2.2737,  3.2973],
         [ 0.0597,  0.6748,  1.6721, -1.9172, -0.9776]],

        [[-0.1259, -0.5863,  0.0144, -3.3686, -1.5376],
         [ 1.4021, -0.4226,  1.0468, -1.5812, -0.8335],
         [-4.3964, -0.3364, -2.0938, -2.6458, -1.9695]],

        [[-1.1418, -0.4550, -1.5601,  0.6462,  0.2754],
         [-1.6614,  0.6957,  4.0230, -0.2799, -0.7121],
         [-1.0671, -0.0169, -1.8942,  1.7611,  2.4917]],

        [[ 0.7832, -1.5725,  3.3583, -0.7314, -0.2346],
         [ 0.3283,  3.0170, -3.2155, -0.7844,  0.6897],
         [ 0.0879, -1.5669,  2.2670,  0.9668,  0.2408]],

        [[ 7.0175,  1.7417,  4.9367, -2.1746, -8.5266],
         [ 1.3775,  0.2433,  1.8862,  0.3734, -4.2286],
    

- batched matrix x matrix

In [36]:
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
result = torch.matmul(t9, t10)

print_info(result)

dtype :  torch.float32
element :  tensor([[[-2.1507e+00, -3.1828e-01,  7.5433e-01, -2.1790e+00, -3.7608e-01],
         [ 3.1887e+00,  1.2730e+00,  1.7544e+00, -4.0364e+00,  2.2332e+00],
         [ 4.9022e+00,  7.5604e-01,  1.0731e+00, -1.9889e+00,  3.0835e+00]],

        [[-8.0583e+00, -1.3431e+00, -4.9410e-01, -5.2546e-02, -4.1094e+00],
         [ 6.6419e+00,  1.1542e+00,  7.6234e-02,  5.4709e-01,  2.8249e+00],
         [ 1.3304e-01,  2.4081e-01,  3.1211e-02,  2.0584e-01,  1.5339e-01]],

        [[ 5.5533e+00,  6.5231e-01,  1.3595e-02,  9.0015e-01,  2.7955e+00],
         [-1.4762e+00,  1.6416e-01,  2.5089e-03, -9.1855e-01, -1.5135e+00],
         [-2.6677e+00, -3.6761e-01,  9.8919e-01, -3.0336e+00, -6.0419e-01]],

        [[ 1.9832e+00,  9.0888e-02,  1.3834e+00, -2.3762e+00,  2.8094e+00],
         [-2.8064e+00, -2.3859e-01, -1.1264e+00,  2.0729e+00, -2.5899e+00],
         [ 4.2635e+00,  3.0905e-01,  1.2380e-01,  1.3577e-01,  2.1435e+00]],

        [[ 3.1451e+00,  1.4084e+00,  2.6376e-0

## Tensor broadcasting

- scalar operations

In [37]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2)

tensor([2., 4., 6.])


- element-wise operations

In [38]:
t3 = torch.tensor([[0, 1], 
                   [2, 4], 
                   [10, 10]])

t4 = torch.tensor([4, 5])
print(t3 - t4)

#[[0, 1],           [[4,5],
# [2, 4],       -    [4,5],
# [10, 10]])         [4,5]]


tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


- broadcasting

In [39]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print("----- + -----")
print(t5 + 2.0)  # t5.add(2.0)
print("")

print("----- - -----")
print(t5 - 2.0)  # t5.sub(2.0)
print("")

print("----- x -----")
print(t5 * 2.0)  # t5.mul(2.0)
print("")

print("----- / -----")
print(t5 / 2.0)  # t5.div(2.0)

----- + -----
tensor([[3., 4.],
        [5., 6.]])

----- - -----
tensor([[-1.,  0.],
        [ 1.,  2.]])

----- x -----
tensor([[2., 4.],
        [6., 8.]])

----- / -----
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


- element-wise power

In [40]:
def normalize(x):
  return x / 255


t6 = torch.randn(3, 28, 28)
result = normalize(t6)

print_info(result)

dtype :  torch.float32
element :  tensor([[[-0.0016,  0.0028,  0.0036,  ..., -0.0006,  0.0031,  0.0031],
         [ 0.0072, -0.0098,  0.0025,  ...,  0.0085,  0.0021,  0.0030],
         [ 0.0005, -0.0025, -0.0012,  ..., -0.0015, -0.0094,  0.0047],
         ...,
         [ 0.0048,  0.0036,  0.0003,  ...,  0.0050, -0.0017,  0.0019],
         [-0.0006,  0.0018, -0.0026,  ..., -0.0010, -0.0038,  0.0019],
         [-0.0009, -0.0046,  0.0066,  ...,  0.0003,  0.0018,  0.0068]],

        [[ 0.0047,  0.0038,  0.0126,  ..., -0.0023,  0.0004, -0.0054],
         [-0.0014,  0.0032,  0.0007,  ...,  0.0023,  0.0031, -0.0046],
         [ 0.0003,  0.0041, -0.0003,  ...,  0.0010, -0.0038, -0.0012],
         ...,
         [-0.0038,  0.0025, -0.0031,  ..., -0.0029,  0.0024, -0.0044],
         [ 0.0043,  0.0036, -0.0014,  ...,  0.0048,  0.0004, -0.0039],
         [ 0.0070, -0.0009, -0.0014,  ..., -0.0026,  0.0054, -0.0035]],

        [[ 0.0027, -0.0004,  0.0037,  ...,  0.0006,  0.0022, -0.0034],
         [-

- special cases

In [41]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print_info(t12)

dtype :  torch.float32
element :  tensor([[[0.6590, 0.4816],
         [0.3480, 0.7727],
         [0.9384, 0.1520]],

        [[0.6590, 0.4816],
         [0.3480, 0.7727],
         [0.9384, 0.1520]],

        [[0.6590, 0.4816],
         [0.3480, 0.7727],
         [0.9384, 0.1520]],

        [[0.6590, 0.4816],
         [0.3480, 0.7727],
         [0.9384, 0.1520]]])
dimension :  3
shape :  torch.Size([4, 3, 2])


In [42]:
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print_info(t14)

dtype :  torch.float32
element :  tensor([[[0.3239, 0.3239],
         [0.7967, 0.7967],
         [0.1779, 0.1779]],

        [[0.3239, 0.3239],
         [0.7967, 0.7967],
         [0.1779, 0.1779]],

        [[0.3239, 0.3239],
         [0.7967, 0.7967],
         [0.1779, 0.1779]],

        [[0.3239, 0.3239],
         [0.7967, 0.7967],
         [0.1779, 0.1779]]])
dimension :  3
shape :  torch.Size([4, 3, 2])


In [43]:
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print_info(t16)

dtype :  torch.float32
element :  tensor([[[0.2420, 0.8747],
         [0.2420, 0.8747],
         [0.2420, 0.8747]],

        [[0.2420, 0.8747],
         [0.2420, 0.8747],
         [0.2420, 0.8747]],

        [[0.2420, 0.8747],
         [0.2420, 0.8747],
         [0.2420, 0.8747]],

        [[0.2420, 0.8747],
         [0.2420, 0.8747],
         [0.2420, 0.8747]]])
dimension :  3
shape :  torch.Size([4, 3, 2])


In [44]:
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1

In [45]:
print(t17)

tensor([[[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]]])


In [46]:
print(t18)

tensor([[[0.5108]],

        [[0.6059]],

        [[0.6122]]])


In [47]:
print_info(t17 + t18) 
# review

dtype :  torch.float32
element :  tensor([[[[1.5108],
          [1.5108],
          [1.5108],
          [1.5108]],

         [[1.6059],
          [1.6059],
          [1.6059],
          [1.6059]],

         [[1.6122],
          [1.6122],
          [1.6122],
          [1.6122]]],


        [[[1.5108],
          [1.5108],
          [1.5108],
          [1.5108]],

         [[1.6059],
          [1.6059],
          [1.6059],
          [1.6059]],

         [[1.6122],
          [1.6122],
          [1.6122],
          [1.6122]]],


        [[[1.5108],
          [1.5108],
          [1.5108],
          [1.5108]],

         [[1.6059],
          [1.6059],
          [1.6059],
          [1.6059]],

         [[1.6122],
          [1.6122],
          [1.6122],
          [1.6122]]],


        [[[1.5108],
          [1.5108],
          [1.5108],
          [1.5108]],

         [[1.6059],
          [1.6059],
          [1.6059],
          [1.6059]],

         [[1.6122],
          [1.6122],
          [1.6122]

In [48]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)

print_info(t19 + 20)
#review

dtype :  torch.float32
element :  tensor([[[[20.],
          [20.],
          [20.],
          [20.]]],


        [[[20.],
          [20.],
          [20.],
          [20.]]],


        [[[20.],
          [20.],
          [20.],
          [20.]]],


        [[[20.],
          [20.],
          [20.],
          [20.]]],


        [[[20.],
          [20.],
          [20.],
          [20.]]]])
dimension :  4
shape :  torch.Size([5, 1, 4, 1])


- math functions

In [49]:
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

torch.Size([3, 1, 7])


In [50]:
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

torch.Size([3, 3, 3])


In [51]:
t25 = torch.empty(5, 2, 4, 1)
t26 = torch.empty(3, 1, 1)
print((t25 + t26))

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [52]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

tensor([5., 5., 5., 5.])


In [53]:

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

tensor([25., 25., 25., 25.])


In [54]:
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([  1.,   4.,  27., 256.])


## Tensor Indexing

`torch.tensor(row, colum)`

In [55]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9])
print(x[:, 1])  # >>> tensor([1, 6, 11])
print(x[1, 2])  # >>> tensor(7)
print(x[:, -1])  # >>> tensor([4, 9, 14)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [56]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [57]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1
print(y)

print(y[1:4, 1:4])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [58]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2])
print(z[1:, 1:3])
print(z[:, 1:])

print("")
print("----- after convet to 0 to specific area-----")
z[1:, 1:3] = 0
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])

----- after convet to 0 to specific area-----
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


## Tensor reshaping

| Operation Type           | Description and Learning Objectives                              |
| -------------------------| ---------------------------------------------------------------- |
| View and Reshape         | Demonstrates reshaping tensors with `view` and `reshape`.        |
| Squeeze and Unsqueeze    | Shows how to modify tensor dimensions using `squeeze` and `unsqueeze`. |
| Flattening               | Illustrates flattening multi-dimensional tensors into one-dimensional tensors. |
| Permute and Transpose    | Explains tensor dimension permutations and transpositions with `permute`, `transpose`, and `t`. |


In [59]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
print_info(t1)
print("")
print(t1)

dtype :  torch.int64
element :  tensor([[1, 2, 3],
        [4, 5, 6]])
dimension :  2
shape :  torch.Size([2, 3])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [60]:
t2 = t1.view(3,2)
print_info(t2)
print("")
print(t2)

dtype :  torch.int64
element :  tensor([[1, 2],
        [3, 4],
        [5, 6]])
dimension :  2
shape :  torch.Size([3, 2])

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [61]:
t3 = t1.reshape(1,6)
print_info(t3)
print("")
print(t3)

dtype :  torch.int64
element :  tensor([[1, 2, 3, 4, 5, 6]])
dimension :  2
shape :  torch.Size([1, 6])

tensor([[1, 2, 3, 4, 5, 6]])


In [62]:
t4 = torch.arange(8).view(2, 4)
print_info(t4)
print("")
print(t4)

dtype :  torch.int64
element :  tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
dimension :  2
shape :  torch.Size([2, 4])

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [63]:
t5 = torch.arange(6).view(2, 3)
print_info(t5)
print("")
print(t5)

dtype :  torch.int64
element :  tensor([[0, 1, 2],
        [3, 4, 5]])
dimension :  2
shape :  torch.Size([2, 3])

tensor([[0, 1, 2],
        [3, 4, 5]])


In [64]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
test = t6.squeeze(-1)

print(t7)
print(t8)
print(test)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
tensor([[1, 2, 3]])


Squeeze function
> Removes all dimensions of siuze 1 or the specified dimension if its size is 1

In [65]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x)

y = torch.squeeze(x)
print(y)

y = torch.squeeze(x, 0)
print(y)

y = torch.squeeze(x, 1)
print(y)

y = torch.squeeze(x, (1, 2, 3))
print(y)

y = torch.squeeze(x, (0,1,2))
print(y)
print(y.size())
#review

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])
torch.Size([2, 2, 1, 2])


Question 
```
y = torch.squeeze(x, (1, 2, 3))
# torch.Size([2, 2, 2])
```

> squeeze default int value of parameter is 1 that mean, it just remove only 1 dimension so x size [2,1,2,1,2] remove only 1 dimesion but they give a range of applying squeez function (1,2,3) that mean, squeez function will be applied only index of x[1:3] so result size is [2,2,2]

In [66]:
t9 = torch.tensor([1,2,3])

t10 = t9.unsqueeze(1)
print(t10)

print("---t9---")
print_info(t9)
print("")
print("---t10---")
print_info(t10)

tensor([[1],
        [2],
        [3]])
---t9---
dtype :  torch.int64
element :  tensor([1, 2, 3])
dimension :  1
shape :  torch.Size([3])

---t10---
dtype :  torch.int64
element :  tensor([[1],
        [2],
        [3]])
dimension :  2
shape :  torch.Size([3, 1])


> Unsquez : add a new dimension to the nesor at the spcified position

dim = n

n = dimension where will add new dimension 

In [67]:
t11 = torch.tensor(
    [[1,2,3],
     [4,5,6]]
)
t12 = t11.unsqueeze(1)

print_info(t12)

dtype :  torch.int64
element :  tensor([[[1, 2, 3]],

        [[4, 5, 6]]])
dimension :  3
shape :  torch.Size([2, 1, 3])


In [68]:
t13 = torch.tensor([[1,2,3],[4,5,6]])
t14 = t13.flatten()
print_info(t14)

dtype :  torch.int64
element :  tensor([1, 2, 3, 4, 5, 6])
dimension :  1
shape :  torch.Size([6])


In [69]:
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print_info(t16)
print("")
print_info(t17)

dtype :  torch.int64
element :  tensor([1, 2, 3, 4, 5, 6, 7, 8])
dimension :  1
shape :  torch.Size([8])

dtype :  torch.int64
element :  tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
dimension :  2
shape :  torch.Size([2, 4])


In [70]:
t18 = torch.randn(2, 3, 5)

print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

#review

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])


Transpose method

In [71]:
# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], 
                    [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)

print(t19)
print(t20)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [72]:
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)
print(t22)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [73]:
t23 = torch.t(t19)  # Shape becomes (3, 2)
print(t23)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


## Tensor Concat

In [87]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1,t2,t3], dim = 1)
print_info(t4)

dtype :  torch.float32
element :  tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])
dimension :  3
shape :  torch.Size([2, 6, 3])


> what if a different matrix shapes?
> > we can't calculate followed by linear algebra theory. so it makes error

In [88]:
test1 = torch.zeros([2,3,1,2])
test2 = torch.zeros([2,1,1,3])
test3 = torch.zeros([3,4,1,2])

t_result = torch.cat([test1,test2,test3], dim = 1)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 3 for tensor number 1 in the list.

In [89]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)

print_info(t7)

dtype :  torch.int64
element :  tensor([0, 1, 2, 3, 4, 5, 6, 7])
dimension :  1
shape :  torch.Size([8])


In [90]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
print_info(t8)

dtype :  torch.int64
element :  tensor([[0, 1, 2],
        [3, 4, 5]])
dimension :  2
shape :  torch.Size([2, 3])


In [91]:
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
print_info(t9)

dtype :  torch.int64
element :  tensor([[ 6,  7,  8],
        [ 9, 10, 11]])
dimension :  2
shape :  torch.Size([2, 3])


In [92]:
t10 = torch.cat((t8, t9), dim=0)
print_info(t10)

dtype :  torch.int64
element :  tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
dimension :  2
shape :  torch.Size([4, 3])


In [93]:
t11 = torch.cat((t8, t9), dim=1)
print_info(t11)

dtype :  torch.int64
element :  tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
dimension :  2
shape :  torch.Size([2, 6])


In [96]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

print(t12)
print("")
print(t13)
print("")
print(t14)

tensor([[0, 1, 2],
        [3, 4, 5]])

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

tensor([[12, 13, 14],
        [15, 16, 17]])


In [98]:
t15 = torch.cat((t12,t13,t14),dim = 0)
print_info(t15)

dtype :  torch.int64
element :  tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
dimension :  2
shape :  torch.Size([6, 3])


> what if use same variable? it will be duplicate for new row or colum?
> > yes

In [99]:
test = torch.cat((t12,t12,t12),dim = 0)
print_info(test)

dtype :  torch.int64
element :  tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
dimension :  2
shape :  torch.Size([6, 3])


In [100]:
t16 = torch.cat((t12, t13, t14), dim=1)
print_info(t16)

dtype :  torch.int64
element :  tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
dimension :  2
shape :  torch.Size([2, 9])


In [109]:
t17 = torch.arange(0,6)
print("arange : ",t17)
t17 = t17.reshape(1,2,3)
print("reshape : ", t17)

print("")
print("")

print_info(t17)


arange :  tensor([0, 1, 2, 3, 4, 5])
reshape :  tensor([[[0, 1, 2],
         [3, 4, 5]]])


dtype :  torch.int64
element :  tensor([[[0, 1, 2],
         [3, 4, 5]]])
dimension :  3
shape :  torch.Size([1, 2, 3])


In [110]:
t18 = torch.arange(6,12).reshape(1,2,3)

In [111]:
t19 = torch.cat((t17,t18), dim = 0)
print_info(t19)

dtype :  torch.int64
element :  tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
dimension :  3
shape :  torch.Size([2, 2, 3])


In [112]:
t20 = torch.cat((t17,t18), dim = 1)
print_info(t20)

dtype :  torch.int64
element :  tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
dimension :  3
shape :  torch.Size([1, 4, 3])


In [114]:
t21 = torch.cat((t17, t18), dim=2)
print_info(t21)

dtype :  torch.int64
element :  tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])
dimension :  3
shape :  torch.Size([1, 2, 6])


result = depend on dim value each matrix will concat 

- example : when dim = 0, shape index[0] is increased 
- example : when dim = 1, shape idnex[1] is increased
- example : when dim = 2, shape idnex[2] is increased

## Torch Stacking

In [115]:
t1 = torch.tensor([[1, 2, 3], 
                   [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], 
                   [10, 11, 12]])

In [118]:
print_info(t1)
print("")
print("")
print_info(t2)

dtype :  torch.int64
element :  tensor([[1, 2, 3],
        [4, 5, 6]])
dimension :  2
shape :  torch.Size([2, 3])


dtype :  torch.int64
element :  tensor([[ 7,  8,  9],
        [10, 11, 12]])
dimension :  2
shape :  torch.Size([2, 3])


In [120]:
t3 = torch.stack([t1, t2], dim=0)
print_info(t3)

dtype :  torch.int64
element :  tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
dimension :  3
shape :  torch.Size([2, 2, 3])


In [125]:
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print_info(t4)

dtype :  torch.int64
element :  tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
dimension :  3
shape :  torch.Size([2, 2, 3])


In [128]:
t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print_info(t5)
print(t5.equal(t6))

dtype :  torch.int64
element :  tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])
dimension :  3
shape :  torch.Size([2, 2, 3])
True


In [130]:
t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print_info(t7)
print(t7.equal(t8))

#review

dtype :  torch.int64
element :  tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])
dimension :  3
shape :  torch.Size([2, 3, 2])
True


In [131]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())

torch.Size([3]) torch.Size([3])


In [133]:
t11 = torch.stack((t9, t10), dim=0)
print_info(t11)

dtype :  torch.int64
element :  tensor([[0, 1, 2],
        [3, 4, 5]])
dimension :  2
shape :  torch.Size([2, 3])


In [134]:
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print_info(t12)
print(t11.equal(t12))

dtype :  torch.int64
element :  tensor([[0, 1, 2],
        [3, 4, 5]])
dimension :  2
shape :  torch.Size([2, 3])
True


In [136]:
t13 = torch.stack((t9, t10), dim=1)
print_info(t13)

dtype :  torch.int64
element :  tensor([[0, 3],
        [1, 4],
        [2, 5]])
dimension :  2
shape :  torch.Size([3, 2])


In [137]:
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True

True


depend on parameter dim, it will be converted that matrix will be concated

- dim = 0 : row
- dim = 1 : colum 

## Tensor vstack hstack

In [141]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))

print_info(t3)

dtype :  torch.int64
element 
 tensor([[1, 2, 3],
        [4, 5, 6]])
dimension :  2
shape :  torch.Size([2, 3])


In [142]:
t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))

print_info(t6)

dtype :  torch.int64
element 
 tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
dimension :  2
shape :  torch.Size([6, 1])


In [143]:
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])

In [144]:
print_info(t7)

dtype :  torch.int64
element 
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
dimension :  3
shape :  torch.Size([2, 2, 3])


In [145]:
t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])

In [146]:
print_info(t8)

dtype :  torch.int64
element 
 tensor([[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
dimension :  3
shape :  torch.Size([2, 2, 3])


In [147]:
t9 = torch.vstack([t7, t8])
print_info(t9)

dtype :  torch.int64
element 
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
dimension :  3
shape :  torch.Size([4, 2, 3])


In [148]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))

print_info(t12)

dtype :  torch.int64
element 
 tensor([1, 2, 3, 4, 5, 6])
dimension :  1
shape :  torch.Size([6])


In [149]:
t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print_info(t15)

#review

dtype :  torch.int64
element 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])
dimension :  2
shape :  torch.Size([3, 2])


In [152]:
t16 = torch.tensor([[[1, 2, 3], 
                     [4, 5, 6]],
                    [[7, 8, 9], 
                     [10, 11, 12]]
])

print_info(t16)

dtype :  torch.int64
element 
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
dimension :  3
shape :  torch.Size([2, 2, 3])


In [155]:
t17 = torch.tensor([[[13, 14, 15], 
                     [16, 17, 18]],
                    [[19, 20, 21], 
                     [22, 23, 24]]
])
print_info(t17)

t18 = torch.hstack([t16, t17])
print_info(t18)

dtype :  torch.int64
element 
 tensor([[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
dimension :  3
shape :  torch.Size([2, 2, 3])
dtype :  torch.int64
element 
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])
dimension :  3
shape :  torch.Size([2, 4, 3])
